name: publish latest image docker

on:
  push:
    branches:
      - main

jobs:

  client-build:

    if: github.repository_owner == 'shadrqen'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%s')"
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.ES_CLIENT }}:latest
